import Head from "next/head";
import { useEffect, useState } from "react";
import { Inter } from "next/font/google";
import { Footer, Landing, Success, Error } from "@/components";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [submitedEmail, setSubmittedEmail] = useState("");
  const [email, setEmail] = useState("");
  const [error, setError] = useState("");
  const [userCount, setUserCount] = useState(0);
  const [newsletterSubmitted, setNewsletterSubmitted] = useState(false);
  useEffect(() => {
    setTimeout(() => setError(""), 5000);
  }, [error]);
  const fetchCount = async () => {
    try {
      const response = await axios.get("/api/waitlist/add");
      setUserCount(response.data);
      if (response.status !== 200) {
        setError("Failed to fetch user count");
      }
      setError("");
    } catch (error: any) {
      setError(error);
    }
  };

  console.log(userCount);

  useEffect(() => {
    fetchCount();
  }, []);

  return (
    <>
      <Head>
        <title>Space messaging</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className="bg-black relative min-h-screen flex flex-col">
        {!newsletterSubmitted && (
          <Landing
            setEmail={setEmail}
            email={email}
            setSubmit={setNewsletterSubmitted}
            setError={setError}
            setSubmittedEmail={setSubmittedEmail}
          />
        )}
        {newsletterSubmitted && (
          <Success count={userCount} email={submitedEmail} />
        )}
        <Footer />
        {error && <Error error={error} />}
      </main>
    </>
  );
}
